name: Release

on:
  push:
    branches:
      - release

jobs:
  release:
    name: Build & Push
    runs-on: ubuntu

    container:
      image: catthehacker/ubuntu:act-22.04

    env:
      SERVER_URL: https://git.snipcola.com
      USERNAME: snipcola
      TAG: git.snipcola.com/snipcola/snipcola-website:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          github-server-url: ${{ env.SERVER_URL }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.SERVER_URL }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.auth }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.TAG }}
          push: true
          context: .
